import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/footer'

export const metadata = {
    title: 'Beije',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className='flex flex-col h-screen w-full bg-main-bg'>  
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
