import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata = {
    title: 'Beije',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className='flex flex-col w-full h-screen bg-main-bg'>  
                <Navbar />
                {children}
            </body>
        </html>
    )
}
